body = {"project_name":"cb-test-process-1",
        "new_existing_account": "I don't yet have an AWS account or I'd like to start a new one",
        "existing_aws_account_number": "161790450448",
        "existing_aws_account_email": "",
        "account_point_of_contact_email": "itarshis@ucdavis.edu",
        "primary_account_email": "itarshis@ucdavis.edu",
        "budget_authority_email": "jboveda@ucdavis.edu",
        "separate_billing_contact": "No",
        "billing_contact_email": "brcamp@ucdavis.edu",
        "separate_technical_contact": "No",
        "technical_contact_email": "tpamsler@ucdavis.edu",
        "uc_davis_account_number": "9-9999998",
        "estimated_spend": "100",
        "purpose": "test",
        "data_types": "Animal research protocols (P3), Building plans and information about the university physical plant (P2)",
        "protection_level_classification": "P3 - Moderate",
        "availability_level_classification": "A2 - Low",
        "confirm_authorization": "true",
        "confirm_purpose": "true",
        "confirm_data": "true",
        "cloud_provider": "aws",
        "request_number": "TEST-09172020",
        "received from": "itarshis@ucdavis.edu",
        "submitted_by_user": "Ira Tarshis"
    }